- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "e99695"
  description: "Extra attention is needed"
- name: "Type: Bug"
  color: "d73a4a"
  description: "Bug or Bug fixes"
- name: "Type: Feature"
  color: "26C6DA"
  description: "New feature or request"
- name: "Type: Change"
  color: "FBCA04"
  description: "Changes to existing feature"
- name: "Type: Documentation"
  color: "0075ca"
  description: "Documentation changes"
- name: "Type: Refactoring"
  color: "FFEE58"
  description: "A code change that neither fixes a bug nor adds a feature"
- name: "Type: Testing"
  color: "FFCA28"
  description: "Adding missing tests or correcting existing tests"
- name: "Type: CI"
  color: "DCE775"
  description: "Changes to CI configuration files and scripts"
- name: "Type: Question"
  color: "d876e3"
  description: "Further information is requested"
- name: "Type: Discussion"
  color: "d876e3"
  description: "General discussion"
- name: "Type: Suggestion"
  color: "d876e3"
  description: "Suggestion or idea"
- name: "Type: Security"
  color: "d73a4a"
  description: "Vulnerability disclosure or Fixing security issue"
- name: "Type: Performance"
  color: "9CCC65"
  description: "Improving performance"
- name: "Type: Dependencies"
  color: "0D47A1"
  description: "Dependency issues or Changes to dependency files"
- name: "Priority: High"
  color: "E53935"
  description: "High priority"
- name: "Priority: Medium"
  color: "fbca04"
  description: "Medium priority"
- name: "Priority: Low"
  color: "0e8a16"
  description: "Low priority"
- name: "Status: Inactive(Abandoned)"
  color: "ffffff"
  description: "The issue or Pull Request is wontfix"
- name: "Status: Inactive(Duplicate)"
  color: "ffffff"
  description: "This issue or Pull Request already exists"
- name: "Status: Inactive(Invalid)"
  color: "ffffff"
  description: "This issue or Pull Request is invalid"
- name: "Status: Blocked"
  color: "ee0701"
  description: "Progress on the issue is Blocked"
- name: "Status: In Progress"
  color: "0e8a16"
  description: "The issue or Pull Request is in progress"
- name: "Status: Completed"
  color: "0e8a16"
  description: "The issue or Pull Request is completed"
- name: "Status: Todo"
  color: "0e8a16"
  description: "The issue or Pull Request is in todo"
- name: 'github_actions'
  color: '000000'
  description: 'Pull requests that update GitHub Actions code'
- name: 'javascript'
  color: '0e8a16'
  description: 'Pull requests that update JavaScript code'
- name: 'PR: In Progress'
  color: '0e8a16'
  description: 'Work is in progress on this pull request'
- name: 'PR: Review'
  color: 'fbca04'
  description: 'Waiting for review from reviewers'
- name: 'PR: Ready'
  color: '2da44e'
  description: 'The pull request is ready and work is complete'
- name: 'PR: Changes Requested'
  color: 'ee0701'
  description: 'Changes have been requested on this pull request'
- name: 'PR: Blocked'
  color: 'ee0701'
  description: 'This pull request is blocked'
- name: 'PR: Merged'
  color: '6f42c1'
  description: 'This pull request has been merged'
