- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "Type: Bug"
  color: "d73a4a"
  description: "Bug or Bug fixes"
- name: "Type: Feature"
  color: "a2eeef"
  description: "New feature or request"
- name: "Type: Documentation"
  color: "0075ca"
  description: "Documentation only changes"
- name: "Type: Refactoring"
  color: "f9d0c4"
  description: "A code change that neither fixes a bug nor adds a feature"
- name: "Type: Testing"
  color: "f9d0c4"
  description: "Adding missing tests or correcting existing tests"
- name: "Type: CI"
  color: "f9d0c4"
  description: "Changes to CI configuration files and scripts"
- name: "Type: Question"
  color: "d876e3"
  description: "Further information is requested"
- name: "Type: Discussion"
  color: "d876e3"
  description: "General discussion"
- name: "Type: Suggestion"
  color: "d876e3"
  description: "Suggestion or idea"
- name: "Type: Security"
  color: "d73a4a"
  description: "Vulnerability disclosure or Fixing security issue"
- name: "Type: Performance"
  color: "f9d0c4"
  description: "Improving performance"
- name: "Type: Dependencies"
  color: "f9d0c4"
  description: "Dependency issues or Changes to dependency files"
- name: "Priority: High"
  color: "d93f0b"
  description: "High priority"
- name: "Priority: Medium"
  color: "fbca04"
  description: "Medium priority"
- name: "Priority: Low"
  color: "0e8a16"
  description: "Low priority"
- name: "Status: Inactive(Abandoned)"
  color: "000000"
  description: "The issue or Pull Request is wontfix"
- name: "Status: Inactive(Duplicate)"
  color: "000000"
  description: "This issue or Pull Request already exists"
- name: "Status: Inactive(Invalid)"
  color: "000000"
  description: "This issue or Pull Request is invalid"
- name: "Status: Blocked"
  color: "ee0701"
  description: "Progress on the issue is Blocked"
- name: "Status: In Progress"
  color: "0e8a16"
  description: "The issue or Pull Request is in progress"
- name: "Status: Completed"
  color: "0e8a16"
  description: "The issue or Pull Request is completed"
- name: "Status: Todo"
  color: "fbca04"
  description: "The issue or Pull Request is in todo"
