name: Issue Status

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - assigned

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TODO_LABEL: "'Status: Todo'"
  IN_PROGRESS_LABEL: "'Status: In Progress'"
  COMPLETED_LABEL: "'Status: Completed'"
  BLOCKED_LABEL: "'Status: Blocked'"
  INVALID_LABEL: "'Status: Inactive(Invalid)'"
  DUPLICATE_LABEL: "'Status: Inactive(Duplicate)'"
  ABANDONED_LABEL: "'Status: Inactive(Abandoned)'"

jobs:
  add_todo_label_on_issue:
    name: Add Todo label # issueが再度開かれたら、Todoに変更
    runs-on: ubuntu-latest
    if: github.event.action == 'reopened'
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [${{ env.TODO_LABEL }}]
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.COMPLETED_LABEL }}
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.INVALID_LABEL }}
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.DUPLICATE_LABEL }}
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.ABANDONED_LABEL }}
            })

  add_in_progress_label_on_issue:
    name: Add In Progress label # 誰かがアサインされたら、In Progressに変更
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [${{ env.IN_PROGRESS_LABEL }}]
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.TODO_LABEL }}
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.BLOCKED_LABEL }}
            })

  add_completed_label_on_issue:
    name: Add Completed label # issueがクローズされたら、Completedに変更
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [${{ env.COMPLETED_LABEL }}]
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.TODO_LABEL }}
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.IN_PROGRESS_LABEL }}
            })

            github.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.BLOCKED_LABEL }}
            })
