name: Issue Status

on:
  issues:
    types:
      - opened
      - closed
      - reopened
      - assigned

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TODO_LABEL: "'Status: Todo'"
  IN_PROGRESS_LABEL: "'Status: In Progress'"
  COMPLETED_LABEL: "'Status: Completed'"
  BLOCKED_LABEL: "'Status: Blocked'"
  INVALID_LABEL: "'Status: Inactive(Invalid)'"
  DUPLICATE_LABEL: "'Status: Inactive(Duplicate)'"
  ABANDONED_LABEL: "'Status: Inactive(Abandoned)'"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Get the event JSON
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.issue) }}
        run: |
          echo "$GITHUB_CONTEXT"

  add_todo_label_on_issue:
    name: Add Todo label # issueが再度開かれたら、Todoに変更
    if: github.event.action == 'reopened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [${{ env.TODO_LABEL }}]
            })

  add_in_progress_label_on_issue:
    name: Add In Progress label # issueがアサインされたら、In Progressに変更
    if: github.event.action == 'assigned'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [${{ env.IN_PROGRESS_LABEL }}]
            })

  add_completed_label_on_issue:
    name: Add Completed label # issueがクローズされたら、Completedに変更
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [${{ env.COMPLETED_LABEL }}]
            })

  remove_todo_label_on_issue:
    name: Remove Todo label # In ProgressまたはCompletedに変更されたら、Todoを削除
    if: "${{ (github.event.action == 'assigned' || github.event.action == 'closed') && contains(github.event.issue.labels.*.name, 'Stauts: Todo') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.TODO_LABEL }}
            })

  remove_in_progress_label_on_issue:
    name: Remove In Progress label # TodoまたはCompletedに変更されたら、In Progressを削除
    if: "${{ (github.event.action == 'reopened' || github.event.action == 'closed') && contains(github.event.issue.labels.*.name, 'Status: In Progress') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.IN_PROGRESS_LABEL }}
            })

  remove_completed_label_on_issue:
    name: Remove Completed label # TodoまたはIn Progressに変更されたら、Completedを削除
    if: "${{ (github.event.action == 'reopened' || github.event.action == 'assigned') && contains(github.event.issue.labels.*.name, 'Status: Completed') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.COMPLETED_LABEL }}
            })

  remove_blocked_label_on_issue:
    name: Remove Blocked label # In ProgressまたはCompleted変更されたら、Blockedを削除
    if: "${{ (github.event.action == 'assigned' || github.event.action == 'closed') && contains(github.event.issue.labels.*.name, 'Status: Blocked') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.BLOCKED_LABEL }}
            })

  remove_inactive_invalid_label_on_issue:
    name: Remove Inactive label # TodoまたはIn Progressに変更されたら、Inactive(Invalid)を削除
    if: "${{ (github.event.action == 'reopened' || github.event.action == 'assigned') && (contains(github.event.issue.labels.*.name, 'Status: Inactive(Invalid)')) }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.INVALID_LABEL }}
            })

  remove_inactive_duplicate_label_on_issue:
    name: Remove Inactive label # TodoまたはIn Progressに変更されたら、Inactive(Duplicate)を削除
    if: "${{ (github.event.action == 'reopened' || github.event.action == 'assigned') && (contains(github.event.issue.labels.*.name, 'Status: Inactive(Duplicate)')) }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.DUPLICATE_LABEL }}
            })

  remove_inactive_abandoned_label_on_issue:
    name: Remove Inactive label # TodoまたはIn Progressに変更されたら、Inactive(Abandoned)を削除
    if: "${{ (github.event.action == 'reopened' || github.event.action == 'assigned') && (contains(github.event.issue.labels.*.name, 'Status: Inactive(Abandoned)')) }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ${{ env.ABANDONED_LABEL }}
            })
