name: Create release tag and release note.

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Pre-Release Note
        id: pre_release
        if: contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc')
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          version: ${{ github.ref_name }}
          publish: true
          prerelease: true
      - name: Create Release Note
        id: release_note
        if: steps.pre_release.conclusion == 'skipped'
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          version: ${{ github.ref_name }}
          publish: true
