name: Create release tag and release note.

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    if: startsWith(github.event.head_commit.message, 'Release ')
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get_version
        run: echo VERSION=${VERSION_TEXT##*Release } >> $GITHUB_OUTPUT
        env:
          VERSION_TEXT: ${{ github.event.head_commit.message }}
      - name: Create Release Note
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          version: ${{ steps.get_version.outputs.VERSION }}
          publish: true
